### ISSUE TITLE
boolean member with value false is not shown in the variables view

### ISSUE THREAD

**Issue by dnouls** [sdbg/sdbg#87] opened 2014-12-01 16:02 UTC
I was debugging a GWT application with sdbg and I could not find a member variable in the variables view under this. I finally found out that the variable only shows up if the field value is true. 
Is this intended behavior ?

**Comment by ivmarkov** [comment] 2015-01-17 16:01
Yes, thanks, this is now a duplicate of #102 
I'm working on #102 ATM.

**Closed by ivmarkov** 2015-01-17 16:01 UTC
Labels: duplicate
